name: node-weather-destroy.yml

# note: workflow_dispatch is only recognized by github after merging to main
# https://github.com/orgs/community/discussions/25219
on: workflow_dispatch

jobs:
  test:
    environment: dev # this and other github environments are configured in Settings > Environments
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: destroy lambda
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AKI }} # TODO: evaluate security of this pattern
        export AWS_SECRET_ACCESS_KEY=${{ secrets.SAK }}
        bash ci-cd/destroy-lambda.sh
