name: Node Github CI

on: [push]

env:
  NODE_VERSION: "22.14.0"

jobs:
  test:
    environment: dev # this and other github environments are configured in Settings > Environments
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install and test
      run: |
        cd node-weather
        npm install
        npm run lint
        npm run check
        npm test
    
    - name: check envar # secrets (Environment secrets) and vars (Environment variables) are configured in the github environment
      run: |
        echo "OUR_LITTLE_SECRET: ${{ secrets.OUR_LITTLE_SECRET }}"
        echo "vars.MY_TITLE: ${{ vars.MY_TITLE }}"

    - name: deploy lambda
      run: |
        cd node-weather
        npm run build
        cp -r node_modules/ dist/src/
        cd dist/src/
        mkdir ../../../tf-lambda/build
        sudo apt install zip -y
        zip ../../../tf-lambda/build/lambda_weather_function.zip *
        cd ../../../tf-lambda
        ls build/
#        terraform apply --auto-approve
# TODO: figure out how to keep tf.state in AWS
